<?php
// $Id$

/**
 * @file
 *   Allows redirection of mobile users to alternate paths
 */
 
 /**
 * Implementation of hook_menu().
 */
	function mobile_redirects_menu() {
  	$items['admin/settings/mobile_redirects'] = array(
  		'file' => 'mobile_redirects.admin.inc',
			'title' => 'Mobile Redirects Settings',
			'description' => 'Set original path and mobile redirect path for mobile redirections',
			'page callback' => 'drupal_get_form',
			'page arguments' => array('mobile_redirects_settings'),
			'access arguments' => array('administer site configuration'),
			'type' => MENU_NORMAL_ITEM,
		);
  
		$items['admin/settings/mobile_redirects/delete'] = array(
			'file' => 'mobile_redirects.delete.inc',
			'title' => 'Delete Mobile Redirects',
			'description' => 'Delete existing mobile redirects',
			'page callback' => 'drupal_get_form',
			'page arguments' => array('mobile_redirects_delete'),
			'access arguments' => array('administer site configuration'),
			'type' => MENU_LOCAL_TASK,
		);
  
		return $items;
	}

	//the following was lifted from http://mobiforge.com/developing/story/lightweight-device-detection-php
	function mobile_redirects_detect() {
		$mobile_browser = '0';
		if(preg_match('/(up.browser|up.link|mmp|symbian|smartphone|midp|wap|phone)/i', strtolower($_SERVER['HTTP_USER_AGENT']))) {
    	$mobile_browser++;
		}
		if((strpos(strtolower($_SERVER['HTTP_ACCEPT']),'application/vnd.wap.xhtml+xml')>0) or ((isset($_SERVER['HTTP_X_WAP_PROFILE']) or isset		($_SERVER['HTTP_PROFILE'])))) {
   		$mobile_browser++;
		}
		$mobile_ua = strtolower(substr($_SERVER['HTTP_USER_AGENT'],0,4));
		$mobile_agents = array(
    'w3c ','acs-','alav','alca','amoi','audi','avan','benq','bird','blac','blaz','brew','cell','cldc','cmd-','dang','doco','eric','hipt','inno','ipaq','java','jigs','kddi','keji','leno','lg-c','lg-d','lg-g','lge-','maui','maxo','midp','mits','mmef','mobi','mot-','moto','mwbp','nec-','newt','noki','oper','palm','pana','pant','phil','play','port','prox','qwap','sage','sams','sany','sch-','sec-','send','seri','sgh-','shar','sie-','siem','smal','smar','sony','sph-','symb','t-mo','teli','tim-','tosh','tsm-','upg1','upsi','vk-v','voda','wap-','wapa','wapi','wapp','wapr','webc','winw','winw','xda','xda-');
    if(in_array($mobile_ua,$mobile_agents)) {
				$mobile_browser++;
			}
			if (strpos(strtolower($_SERVER['ALL_HTTP']),'operamini')>0) {$mobile_browser++;
			}
			if (strpos(strtolower($_SERVER['HTTP_USER_AGENT']),' ppc;')>0) {
				$mobile_browser++;}if (strpos(strtolower($_SERVER['HTTP_USER_AGENT']),'windows ce')>0) {
					$mobile_browser++;
				} else if (strpos(strtolower($_SERVER['HTTP_USER_AGENT']),'windows')>0) {
					$mobile_browser=0;
				}
				if (strpos(strtolower($_SERVER['HTTP_USER_AGENT']),'iemobile')>0) {
					$mobile_browser++;
				}
			if($mobile_browser>0) {
				//after all detection anything greater than 0 means mobile. so we return true.
			return TRUE;
		} 
	}
  
	//once we've determined it's a mobile user we can make stuff happen
 	if (mobile_redirects_detect()) 	{
		//find the current path
		$path = drupal_get_path_alias($_GET['q']);
		$theresult = db_result(db_query('SELECT redirect FROM {mobile_redirects} WHERE path ="%s"', $path));
		if(!empty($theresult)) {
			drupal_goto($theresult);
		};
	}  	